### ISSUE TITLE
Missing files (?)

### ISSUE THREAD

**Issue by echo66** [arimai/meal-planner#1]
Greetings! 

Thanks for creating a really nice, and intuitive, demo for Edamam API!

I'm trying to use the demo in my local machine. Unfortunately, I'm getting this error when I access localhost:3000:

```
Failed to compile
./src/utils/data/index.js
Module not found: Can't resolve '../../data' in '/home/echo66/tripleg/third-party-demos/meal-planner/src/utils/data'
This error occurred during the build time and cannot be dismissed.
```

My suspicion is that this is the results of some files you didn't commit.

**Comment by arimai** [comment]
Hi echo66,Thank you!You are right I didn't commit the data file I was using to
build my app.You should be able to use it now, I made the changes.Just in case
you see a 404 page or no values returned, don't worry, you just have to get an
id and key for yourself from the Edamam API and just replace those values in the
data.js file.
If you still get issues, please feel free to email me!






On Fri, Mar 30, 2018 10:20 AM, echo66 notifications@github.com  wrote:
Greetings!

Thanks for creating a really nice, and intuitive, demo for Edamam API!

I'm trying to use the demo in my local machine. Unfortunately, I'm getting this
error when I access localhost:3000:

Failed to compile
./src/utils/data/index.js
Module not found: Can't resolve '../../data' in '/home/echo66/tripleg/third-party-demos/meal-planner/src/utils/data'
This error occurred during the build time and cannot be dismissed.


My suspicion is that this is the results of some files you didn't commit.
